version: '3'

services:
  redis:
    build:
      context: ./redis
    container_name: my-redis
    ports:
      - "6379:6379"
    networks:
      - my-mosquitto

  mosquitto:
    build:
      context: ./mqtt_broker
    container_name: my-mosquitto
    volumes:
      - ./mqtt_broker/config:/mosquitto/config
      - ./mqtt_broker/data:/mosquitto/data
      - ./mqtt_broker/log:/mosquitto/log
    ports:
      - "1883:1883"
    networks:
      - my-mosquitto

  mongodb:
    build:
      context: ./mongodb
    container_name: my-mongodb
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - my-mosquitto
    extra_hosts:
      - "host.docker.internal:host-gateway"

  device_01:
    build:
      context: ./publishers/sensor
    container_name: device_01
    networks:
      - my-mosquitto
    environment:
    - SENSOR_ID=sensor_temperature_01
    - SENSOR_TYPE=temperature
    - PYTHONUNBUFFERED=1

  device_02:
    build:
      context: ./publishers/sensor
    container_name: device_02
    networks:
      - my-mosquitto
    environment:
    - SENSOR_ID=sensor_temperature_02
    - SENSOR_TYPE=temperature
    - PYTHONUNBUFFERED=1

  device_03:
    build:
      context: ./publishers/sensor
    container_name: device_03
    networks:
      - my-mosquitto
    environment:
    - SENSOR_ID=sensor_humidity_01
    - SENSOR_TYPE=humidity
    - PYTHONUNBUFFERED=1

  device_04:
    build:
      context: ./publishers/sensor
    container_name: device_04
    networks:
      - my-mosquitto
    environment:
    - SENSOR_TYPE=humidity
    - SENSOR_ID=sensor_humidity_02
    - PYTHONUNBUFFERED=1

  subscriber:
    build:
      context: ./subscribers
    container_name: subscriber
    networks:
      - my-mosquitto
    environment:
    - SENSOR_TYPES=humidity,temperature
    - PYTHONUNBUFFERED=1
    depends_on:
      - mosquitto
      - mongodb

networks:
  my-mosquitto:
    driver: bridge

volumes:
  mongodb-data: